---
- name: Configure NTP on Brocade ICX switch
  hosts: "{{ target_hosts | default('sw_uart') }}"
  gather_facts: false

  tasks:
    - name: Add NTP server
      bofzilla.icx.ntp:
        servers:
          - 134.59.1.5
        enabled: true
        save_when: changed
        enable_password: "{{ icx_enable_password | default(omit) }}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        var: result
